// <auto-generated />
namespace SH.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RegisterTblChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegisterTblChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202307170632123_RegisterTblChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
